// Generated by CoffeeScript 1.6.3
(function() {
  var ApiMate, bindTooltips, isFilled, pad, postErrorTemplate, postSuccessTemplate, preUploadUrl, template;

  template = "<div class='result-set'>     <div class='result-title'>       <h5 class='label-title'>Results {{title}}:</h5>     </div>     <div class='result-links'>       {{#urls}}         <div class='result-link-wrapper'>         <div class='result-link {{urlClass}}'>           <a href='#' data-url='{{url}}' class='api-link-post tooltipped label' title='Send \"{{name}}\" using a POST request'>             post           </a>           <span class='method-name'>{{name}}</span>           <a class='api-link' href='{{url}}'>{{urlName}}</a>         </div>         </div>       {{/urls}}     </div>   </div>";

  postSuccessTemplate = "<pre>{{response}}</pre>";

  postErrorTemplate = "<p>Server responded with status: <code>{{status}}: {{statusText}}</code>.</p>   {{#response}}     <p>Content:</p>     <pre>{{response}}</pre>   {{/response}}   {{^response}}     <p>Content: <code>-- no content --</code></p>   {{/response}}   <p>If you don't know the reason for this error, check these possibilities:</p>   <ul>     <li>       Your server does not allow <strong>cross-domain requests</strong>. By default BigBlueButton and Mconf-Live <strong>do not</strong> allow cross-domain       requests, so you have to enable it to test this request via POST. Check our <a href=\"https://github.com/mconf/api-mate/tree/master#allow-cross-domain-requests-for-post-requests\">README</a>       for instructions on how to do it.     </li>     <li>       This API method cannot be accessed via POST.     </li>     <li>       Your server is down or malfunctioning. Log into it and check if everything is OK with <code>bbb-conf --check</code>.     </li>   <ul>";

  preUploadUrl = "<?xml version='1.0' encoding='UTF-8'?>     <modules>       <module name='presentation'>         <document url='{{url}}' />       </module>     </modules>";

  ApiMate = (function() {
    function ApiMate() {
      this.updatedTimer = null;
    }

    ApiMate.prototype.configure = function() {
      var _this = this;
      this.setInitialValues();
      $("#input-id").on("keyup", function() {
        return $("#input-name").val($(this).val());
      });
      $("input, select, textarea", "#config-fields").on("change keyup", function(e) {
        return _this.generateUrls();
      });
      $("input, select, textarea", "#config-server").on("change keyup", function(e) {
        return _this.generateUrls();
      });
      $("#view-type-input").on("click", function() {
        var selected;
        selected = !$("#view-type-input").hasClass("active");
        return _this.expandLinks(selected);
      });
      $("input[name='document']").on("change", function() {
        var val;
        val = $("input[name='document']:checked").attr('value');
        if (val === 'url') {
          $("#pre-upload-url").show();
          return $("#pre-upload-text").hide();
        } else if (val === 'text') {
          $("#pre-upload-text").show();
          return $("#pre-upload-url").hide();
        }
      });
      $(".api-mate-clearall").on("click", function(e) {
        _this.clearAllFields();
        return _this.generateUrls();
      });
      return this.generateUrls();
    };

    ApiMate.prototype.setInitialValues = function() {
      var name, user, vbridge;
      vbridge = "7" + pad(Math.floor(Math.random() * 10000 - 1).toString(), 4);
      $("#input-voice-bridge").val(vbridge);
      name = "random-" + Math.floor(Math.random() * 10000000).toString();
      $("#input-name").val(name);
      $("#input-id").val(name);
      user = "User " + Math.floor(Math.random() * 10000000).toString();
      return $("#input-fullname").val(user);
    };

    ApiMate.prototype.addUrlsToPage = function(urls) {
      var html, opts, placeholder;
      placeholder = $("#api-mate-results");
      urls = _.map(urls, function(url, key) {
        var u;
        u = {
          name: key,
          url: url,
          urlName: url
        };
        if (key.match(/recordings/i)) {
          u.urlClass = "url-recordings";
        } else if (key.match(/from mobile/i)) {
          u.urlClass = "url-from-mobile";
        } else if (key.match(/mobile:/i)) {
          u.urlClass = "url-mobile-api";
        } else if (key.match(/custom call/i)) {
          u.urlClass = "url-custom-call";
        } else {
          u.urlClass = "url-standard";
        }
        return u;
      });
      opts = {
        title: new Date().toTimeString(),
        urls: urls
      };
      html = Mustache.to_html(template, opts);
      $(placeholder).html(html);
      this.expandLinks($("#view-type-input").hasClass("active"));
      placeholder.addClass("updated");
      clearTimeout(this.updatedTimer);
      return this.updatedTimer = setTimeout(function() {
        return placeholder.removeClass("updated");
      }, 300);
    };

    ApiMate.prototype.getApi = function() {
      var server;
      server = {};
      server.url = $("#input-custom-server-url").val();
      server.salt = $("#input-custom-server-salt").val();
      server.mobileSalt = $("#input-custom-server-mobile-salt").val();
      server.url = server.url.replace(/(\/api)?\/?$/, '/api');
      server.name = server.url;
      return new BigBlueButtonApi(server.url, server.salt, server.mobileSalt);
    };

    ApiMate.prototype.generateUrls = function() {
      var api, customCalls, line, lines, paramName, paramValue, params, separator, urls, _i, _j, _len, _len1;
      params = {};
      if (isFilled("#input-name")) {
        params.name = $("#input-name").val();
      }
      if (isFilled("#input-id")) {
        params.meetingID = $("#input-id").val();
      }
      if (isFilled("#input-moderator-password")) {
        params.moderatorPW = $("#input-moderator-password").val();
      }
      if (isFilled("#input-attendee-password")) {
        params.attendeePW = $("#input-attendee-password").val();
      }
      if (isFilled("#input-welcome")) {
        params.welcome = $("#input-welcome").val();
      }
      if (isFilled("#input-voice-bridge")) {
        params.voiceBridge = $("#input-voice-bridge").val();
      }
      if (isFilled("#input-dial-number")) {
        params.dialNumber = $("#input-dial-number").val();
      }
      if (isFilled("#input-web-voice")) {
        params.webVoice = $("#input-web-voice").val();
      }
      if (isFilled("#input-logout-url")) {
        params.logoutURL = $("#input-logout-url").val();
      }
      if (isFilled("#input-max-participants")) {
        params.maxParticipants = $("#input-max-participants").val();
      }
      if (isFilled("#input-duration")) {
        params.duration = $("#input-duration").val();
      }
      params.record = $("#input-record").is(":checked");
      if (isFilled("#input-fullname")) {
        params.fullName = $("#input-fullname").val();
      }
      if (isFilled("#input-user-id")) {
        params.userID = $("#input-user-id").val();
      }
      if (isFilled("#input-create-time")) {
        params.createTime = $("#input-create-time").val();
      }
      if (isFilled("#input-web-voice-conf")) {
        params.webVoiceConf = $("#input-web-voice-conf").val();
      }
      if (isFilled("#input-id")) {
        params.recordID = $("#input-id").val();
      }
      params.publish = $("#input-publish").is(":checked");
      if (isFilled("#input-meta")) {
        lines = $("#input-meta").val().replace(/\r\n/g, "\n").split("\n");
        for (_i = 0, _len = lines.length; _i < _len; _i++) {
          line = lines[_i];
          separator = line.indexOf("=");
          if (separator >= 0) {
            paramName = line.substring(0, separator);
            paramValue = line.substring(separator + 1, line.length);
            params["meta_" + paramName] = paramValue;
          }
        }
      }
      if (isFilled("#input-custom")) {
        lines = $("#input-custom").val().replace(/\r\n/g, "\n").split("\n");
        for (_j = 0, _len1 = lines.length; _j < _len1; _j++) {
          line = lines[_j];
          separator = line.indexOf("=");
          if (separator >= 0) {
            paramName = line.substring(0, separator);
            paramValue = line.substring(separator + 1, line.length);
            params["custom_" + paramName] = paramValue;
          }
        }
      }
      customCalls = null;
      if (isFilled("#input-custom-calls")) {
        lines = $("#input-custom-calls").val().replace(/\r\n/g, "\n").split("\n");
        customCalls = lines;
      }
      api = this.getApi();
      urls = api.getUrls(params, customCalls);
      this.addUrlsToPage(urls);
      this.bindPostRequests();
      return bindTooltips();
    };

    ApiMate.prototype.clearAllFields = function() {
      $("#config-fields input, #config-fields textarea").each(function() {
        return $(this).val("");
      });
      return $("#config-fields input[type=checkbox]").each(function() {
        return $(this).attr("checked", null);
      });
    };

    ApiMate.prototype.expandLinks = function(selected) {
      if (selected) {
        return $("#api-mate-results .result-link").addClass('expanded');
      } else {
        return $("#api-mate-results .result-link").removeClass('expanded');
      }
    };

    ApiMate.prototype.bindPostRequests = function() {
      var _apiMate;
      _apiMate = this;
      return $(document).on('click', 'a.api-link-post', function(e) {
        var $target, href;
        $target = $(this);
        href = $target.attr('data-url');
        $('.api-link-post').addClass('disabled');
        $.ajax({
          url: href,
          type: "POST",
          crossDomain: true,
          contentType: "application/xml; charset=utf-8",
          dataType: "xml",
          data: _apiMate.getPostData(),
          complete: function(jqxhr, status) {
            var html, opts;
            if (jqxhr.status === 200) {
              $('#post-response-modal .modal-header').removeClass('alert-danger');
              $('#post-response-modal .modal-header').addClass('alert-success');
              html = Mustache.to_html(postSuccessTemplate, {
                response: jqxhr.responseText
              });
              $('#post-response-modal .modal-body').html(html);
            } else {
              $('#post-response-modal .modal-header h4').text('Ooops!');
              $('#post-response-modal .modal-header').addClass('alert-danger');
              $('#post-response-modal .modal-header').removeClass('alert-success');
              opts = {
                status: jqxhr.status,
                statusText: jqxhr.statusText
              };
              if (!_.isEmpty(jqxhr.responseText)) {
                opts['response'] = jqxhr.responseText;
              }
              html = Mustache.to_html(postErrorTemplate, opts);
              $('#post-response-modal .modal-body').html(html);
            }
            $('#post-response-modal').modal({
              show: true
            });
            return $('.api-link-post').removeClass('disabled');
          }
        });
        e.preventDefault();
        return false;
      });
    };

    ApiMate.prototype.getPostData = function() {
      var opts, url, val;
      val = $("input[name='document']:checked").attr('value');
      if (val === 'url') {
        url = $('#input-pre-upload-url').val();
      }
      if ((url != null) && !_.isEmpty(url)) {
        opts = {
          url: url
        };
        return Mustache.to_html(preUploadUrl, opts);
      }
    };

    return ApiMate;

  })();

  isFilled = function(field) {
    var value;
    value = $(field).val();
    return (value != null) && value.trim() !== "";
  };

  pad = function(num, size) {
    var s;
    s = "0000" + num;
    return s.substr(s.length - size);
  };

  bindTooltips = function() {
    var defaultOptions;
    defaultOptions = {
      container: 'body',
      placement: 'top'
    };
    return $('.tooltipped').tooltip(defaultOptions);
  };

  $(function() {
    var apiMate;
    apiMate = new ApiMate();
    return apiMate.configure();
  });

}).call(this);
